# base this image of the SQL 2017 latest image
FROM microsoft/mssql-server-linux:latest
 
# make a directory within the container
RUN mkdir /var/opt/sqlserver
 
# copy attach-db.sh into container
COPY attach-db.sh /var/opt/sqlserver
 
# copy database files into container
COPY DatabaseA.mdf /var/opt/sqlserver
COPY DatabaseA_log.ldf /var/opt/sqlserver
 
# use the ENTRYPOINT command to execute the script and start SQL Server
ENTRYPOINT /var/opt/sqlserver/attach-db.sh & /opt/mssql/bin/sqlservr